// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fplatxpgpqyxuxsqjsgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwbGF0eHBncHF5eHV4c3Fqc2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDAwOTYsImV4cCI6MjA2ODkxNjA5Nn0.cmU-XNlftY7paRVN1vr3IPT3HaDZdsHbsHvHLpVGsSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});